version: '3.8'

services:
  # 1. SERVICE BACKEND (Python Uvicorn)
  backend-api:
    build:
      context: .
      dockerfile: ./api/app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db-server
      - DB_PORT=3306                     # Port standar MySQL
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}       # Mengambil dari file .env lokal
    networks:
      - tim-network
    depends_on:
      - db-server

  # 2. SERVICE FRONTEND (CodeIgniter 4)
  frontend-web:
    build:
      context: ./project
      dockerfile: ./Dockerfile           # Mengarah ke Dockerfile CI4 di dalam folder project
    ports:
      - "8080:80"
    environment:
      # URL untuk PHP server-side (di dalam Docker, pakai nama service)
      - API_URL=http://backend-api:8000
      # URL untuk JavaScript di browser (diakses dari luar Docker, pakai localhost)
      - API_URL_BROWSER=http://localhost:8000
    volumes:
      # === [ BIND MOUNT ] ===
      # Memetakan folder assets lokal ke folder target aset publik di dalam kontainer Apache
      - ./project/public/assets:/var/www/html/public/assets
    networks:
      - tim-network
    depends_on:
      - backend-api

  # 3. SERVICE LOGS (Product Lead - Monitoring Error Logs)
  logs-monitor:
    image: busybox
    volumes:
      # === [ BIND MOUNT ] ===
      # Memetakan folder logs lokal agar Product Lead bisa lihat error logs langsung dari VS Code
      - ./project/writable/logs:/logs
    command: tail -F /logs/application.log
    networks:
      - tim-network
    depends_on:
      - frontend-web

  # 4. SERVICE DATABASE (MySQL 8)
  db-server:
    image: mysql:8                     # SUDAH DIGANTI MENJADI MYSQL SAKTI
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} # Password root MySQL
    volumes:
      # === [ NAMED VOLUME ] ===
      # Menyimpan data database MySQL tim secara aman di volume internal Docker
      - database-tim-volume:/var/lib/mysql
    networks:
      - tim-network

# DEFINISI NAMED VOLUME GLOBAL (Syarat Wajib Laporan Kelompok)
volumes:
  database-tim-volume:

networks:
  tim-network:
    driver: bridge