version: '3.8'

services:
  web-app:
    image: ghcr.io/nama-tim-anda/mvc-app:v1.0.0 # Merujuk pada image stabil tim
    container_name: mvc-production-app
    ports:
      - "80:5000" # Mengarahkan port 80 (HTTP standar) ke port internal aplikasi
    environment:
      - NODE_ENV=production
      - DB_HOST=db-prod
      - DB_USER=${PROD_DB_USER}       # Mengambil dari file .env produksi di server
      - DB_PASSWORD=${PROD_DB_PASSWORD} # Mengambil dari file .env produksi di server
      - DB_NAME=${PROD_DB_NAME}
    depends_on:
      - db-prod
    restart: always

  db-prod:
    image: mysql:8
    container_name: mysql-production-db
    environment:
      MYSQL_ROOT_PASSWORD: ${PROD_DB_PASSWORD}  # Menggunakan password root MySQL dari .env
      MYSQL_DATABASE: ${PROD_DB_NAME}           # Membuat database otomatis saat up
    volumes:
      - database-tim-volume:/var/lib/mysql 
    restart: always

volumes:
  database-tim-volume: